name: notes
channels:
  - conda-forge
dependencies:
  - pip
  - python
  - sphinx
  - sphinx-book-theme
  - nbsphinx
  - jupyterlab
  - pre-commit
  - pip:
    - jupyterlab-vim
    - sphinxcontrib-jquery
