name: Build and Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pandoc/actions/setup@v1
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install .
    - name: Sphinx build
      run: |
        cd notes
        make clean html
        cd ..
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/artifact-build'
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: notes/build/html
        force_orphan: true

