name: Deploy to GitHub Pages
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install .
    - name: Sphinx build
      run: |
        cd notes
        make clean html
        cd ..
    - name: Add docs to gh-pages branch
      run: |
        git checkout --orphan gh-pages
        git rm -rf .
        mv notes/build .
        git add build
        git commit -v "Add built docs"
