name: Deploy to GitHub Pages
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install dependencies
      run: |
        sudo apt install pandoc
        python3 -m pip install --upgrade pip
        pip install .
    - name: Sphinx build
      run: |
        cd notes
        make clean html
        cd ..
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/
        force_orphan: true
